# Generated by Django 3.0 on 2022-03-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200316_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='confirm_password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
