# Generated by Django 3.0 on 2022-03-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player2',
            name='Player_name',
        ),
        migrations.AddField(
            model_name='player',
            name='Player_username',
            field=models.CharField(default='test', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='player2',
            name='Player_username',
            field=models.CharField(default='t', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
