# Generated by Django 3.0 on 2022-03-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220328_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('Fan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Fan_name', models.CharField(max_length=30)),
                ('Fan_username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Course_Taken',
        ),
    ]
