# Generated by Django 3.0 on 2022-03-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerForgot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
