# Generated by Django 3.0 on 2022-04-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_fanforgot_staffforgot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fan2',
        ),
        migrations.DeleteModel(
            name='FanForgot',
        ),
        migrations.DeleteModel(
            name='StaffForgot',
        ),
        migrations.RenameField(
            model_name='fan',
            old_name='Fan_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='fan',
            old_name='Fan_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fan',
            old_name='Fan_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Player_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Player_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Player_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='player2',
            old_name='Player_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='Staff_username',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
