# Generated by Django 3.0 on 2022-04-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_forgot_reset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player2',
            new_name='Find',
        ),
    ]
