# Generated by Django 3.0 on 2022-04-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20220401_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerForgot',
        ),
        migrations.RemoveField(
            model_name='reset',
            name='username',
        ),
        migrations.AddField(
            model_name='reset',
            name='email',
            field=models.CharField(default='t', max_length=30),
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.CharField(default='t', max_length=30),
        ),
    ]
