# Generated by Django 3.0 on 2022-04-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20220401_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
