# Generated by Django 3.0 on 2022-04-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_expense', models.CharField(max_length=30)),
                ('department_name', models.CharField(max_length=30)),
                ('expense_name', models.CharField(max_length=30)),
                ('expense_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=100)),
                ('news_main', models.CharField(max_length=500)),
                ('news_date', models.DateField()),
                ('news_image', models.ImageField(upload_to='news')),
                ('news_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Month', models.CharField(choices=[('January', 'January'), ('February', 'Fenruary'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Revenue', models.BooleanField(max_length=30)),
                ('Expenses', models.BooleanField(max_length=30)),
                ('Customer_Purchases', models.BooleanField(max_length=30)),
                ('Development_Cost', models.BooleanField(max_length=30)),
                ('Calculated_Difference', models.BooleanField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('merch_name', models.CharField(max_length=30)),
                ('merch_date', models.CharField(max_length=30)),
                ('merch_price', models.CharField(max_length=30)),
                ('ticket_name', models.CharField(max_length=30)),
                ('ticket_date', models.CharField(max_length=30)),
                ('ticket_price', models.CharField(max_length=30)),
            ],
        ),
    ]
