# Generated by Django 3.2.12 on 2022-04-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_expense', models.CharField(max_length=30)),
                ('department_name', models.CharField(max_length=30)),
                ('expense_name', models.CharField(max_length=30)),
                ('expense_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('merch_name', models.CharField(max_length=30)),
                ('merch_date', models.CharField(max_length=30)),
                ('merch_price', models.CharField(max_length=30)),
                ('ticket_name', models.CharField(max_length=30)),
                ('ticket_date', models.CharField(max_length=30)),
                ('ticket_price', models.CharField(max_length=30)),
            ],
        ),
    ]
