# Generated by Django 3.0 on 2022-04-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_expenses_news_report_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(null=True),
        ),
    ]
