# Generated by Django 3.2.12 on 2022-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20220405_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Calculated_Difference',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Customer_Purchases',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Development_Cost',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Expenses',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Revenue',
        ),
        migrations.AlterField(
            model_name='report',
            name='Month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=30),
        ),
    ]
