# Generated by Django 3.2.12 on 2022-04-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20220406_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='department_name',
            field=models.CharField(default='hi', max_length=30),
        ),
    ]
