# Generated by Django 3.0 on 2022-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20220407_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('card_number', models.IntegerField()),
                ('experation_date', models.DateField()),
                ('CCV', models.IntegerField()),
            ],
        ),
    ]
