# Generated by Django 3.0 on 2022-04-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_cartm_merchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='news_image',
            field=models.ImageField(default=1, upload_to='merch'),
            preserve_default=False,
        ),
    ]
