# Generated by Django 3.0 on 2022-04-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_auto_20220407_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='CartM',
        ),
    ]
