# Generated by Django 3.0 on 2022-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='experation_date',
            field=models.CharField(max_length=5),
        ),
    ]
