# Generated by Django 3.0 on 2022-04-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_auto_20220409_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_logo',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
