# Generated by Django 3.0 on 2022-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20220409_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1_logo',
            field=models.ImageField(blank=True, null=True, upload_to='matches'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='matches'),
        ),
    ]
