# Generated by Django 3.0 on 2022-04-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20220409_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Calculated_Difference',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Customer_Purchases',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Development_Cost',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Expenses',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Revenue',
        ),
        migrations.AddField(
            model_name='revenue',
            name='department_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='Month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=30),
        ),
    ]
