# Generated by Django 3.2.12 on 2022-04-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20220409_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
