# Generated by Django 3.2.12 on 2022-04-13 19:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_auto_20220413_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_title', models.CharField(max_length=200)),
                ('streaming_body', models.TextField()),
                ('streaming_video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'Streaming',
            },
        ),
    ]
