# Generated by Django 3.2.12 on 2022-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_streaming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('league_team1', models.CharField(max_length=100)),
                ('league_team2', models.CharField(max_length=100)),
                ('league_team3', models.CharField(max_length=100)),
                ('league_team4', models.CharField(max_length=100)),
                ('league_team5', models.CharField(max_length=100)),
                ('league_t1_points', models.IntegerField()),
                ('league_t2_points', models.IntegerField()),
                ('league_t3_points', models.IntegerField()),
                ('league_t4_points', models.IntegerField()),
                ('league_t5_points', models.IntegerField()),
            ],
        ),
    ]
