# Generated by Django 3.2.12 on 2022-04-20 15:11

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_streaming'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguesMen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaguesWomen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Streaming',
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Match'},
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='news_image',
        ),
        migrations.AddField(
            model_name='match',
            name='streaming_body',
            field=models.TextField(default='foo'),
        ),
        migrations.AddField(
            model_name='match',
            name='streaming_title',
            field=models.CharField(default='foo', max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='streaming_video',
            field=embed_video.fields.EmbedVideoField(default='foo'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='item_image',
            field=models.ImageField(default='foo', upload_to='merch'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='id',
            field=models.IntegerField(default='foo', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='item_name',
            field=models.CharField(default='foo', max_length=30),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.IntegerField(default='foo'),
        ),
    ]
