# Generated by Django 3.0 on 2022-04-25 15:17

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_auto_20220420_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='num_tickets',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='streaming_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='streaming_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='match',
            name='streaming_video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
