# Generated by Django 3.0 on 2022-04-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_auto_20220414_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leagues',
            old_name='league_t1_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='leagues',
            old_name='league_team1',
            new_name='team_name',
        ),
    ]
