# Generated by Django 3.0 on 2022-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_auto_20220425_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='num_tickets',
            new_name='num_ticketsA',
        ),
        migrations.AddField(
            model_name='match',
            name='num_ticketsB',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='num_ticketsC',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
