# Generated by Django 3.0 on 2022-04-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_auto_20220414_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguesWomen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Leagues',
            new_name='LeaguesMen',
        ),
    ]
