# Generated by Django 3.0 on 2022-04-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_auto_20220414_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchandise',
            old_name='news_image',
            new_name='item_image',
        ),
    ]
