# Generated by Django 3.0 on 2022-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_auto_20220425_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
