# Generated by Django 3.0 on 2022-04-28 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_auto_20220427_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenue',
            old_name='merch_date',
            new_name='item_amount',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='merch_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='merch_price',
            new_name='item_price',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='ticket_date',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='ticket_name',
        ),
        migrations.RemoveField(
            model_name='revenue',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='revenue',
            name='item_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
