# Generated by Django 3.0 on 2022-04-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_auto_20220428_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='item_date',
            field=models.CharField(max_length=30),
        ),
    ]
